export enum E_BINANCE_ORDER_STATUS {
  PARTIALLY_FILLED = 'PARTIALLY_FILLED',
  EXPIRED_IN_MATCH = 'EXPIRED_IN_MATCH',
  PENDING_CANCEL = 'PENDING_CANCEL',
  PENDING_NEW = 'PENDING_NEW',
  CANCELED = 'CANCELED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  FILLED = 'FILLED',
  NEW = 'NEW',
}
