export enum E_BINANCE_RATE_LIMIT_TYPE {
  REQUEST_WEIGHT = 'REQUEST_WEIGHT',
  RAW_REQUESTS = 'RAW_REQUESTS',
  ORDERS = 'ORDERS',
}

export enum E_BINANCE_RATE_LIMIT_TYPE_INTERVAL {
  SECOND = 'SECOND',
  MINUTE = 'MINUTE',
  DAY = 'DAY'
}
